name: Test

on:
  - pull_request

env:
  BEAKER_HYPERVISOR: docker

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.4"
          - "2.5"
          - "2.6"
          - "2.7"
          - "3.0"
          - "3.1"
    env:
      BUNDLE_WITHOUT: release
    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Verify gem builds
        run: bundle exec gem build beaker-rspec.gemspec
      - name: Run acceptance tests
        run: bundle exec rake beaker
