name: Test

on:
  pull_request: {}
  push:
    branches:
      - master

env:
  BUNDLE_WITHOUT: release
  BEAKER_HYPERVISOR: docker

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
      - name: Run Rubocop
        run: bundle exec rake rubocop
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Verify gem builds
        run: gem build --strict --verbose *.gemspec
      - name: Run acceptance tests
        run: bundle exec rake beaker

  tests:
    needs:
      - rubocop
      - build
    runs-on: ubuntu-latest
    name: Test suite
    steps:
      - run: echo Test suite completed
